Routing with react-router
memeoplast/react-app pull request #4
Opened 2023-08-02 13:35 UTC by memeoplast

2023-08-02 13:36 UTC, memeoplast commented on src/Routes/Contact.jsx
Dummy Placeholder für Kontaktformular. Kann erstmal ignoriert werden.

2023-08-02 13:41 UTC, memeoplast commented on src/Components/Navbar/Navbar.jsx
@Juviro `  onClick={() => handleScrollToElement("Pricing")}` soll zur id die in einem <div> innerhalb einer Komponente scrollen. Hier also zur Pricing Komponente auf der Landing Page.  Zur "/" route kommt man aber scrolling geht nicht.  Ist `() => handleScrollToElement("Pricing")` hier richtig?

2023-08-07 15:57 UTC, Juviro requested changes

2023-08-07 15:57 UTC, Juviro commented on src/App.jsx
> +  const contacts = await getContacts();
**todo:** getContacts ist nicht definiert

2023-08-07 15:57 UTC, Juviro commented on src/App.jsx
> +      <div id="components__container">
**question:** Wird diese id verwendet? Falls nein -> raus damit

2023-08-07 15:57 UTC, Juviro commented on src/Components/Button/Button.jsx
> +    <Link to={url} className="button__big" rel="noreferrer">
**todo:** `big` ist ein Zustand, ich würde die Klasse hier also `button--big` (oder `button--large`, etwas geläufiger) nennen

2023-08-07 15:57 UTC, Juviro commented on src/Components/Button/Button.jsx
>  const Button__link = ({ text, url }) => {
**todo:** Komponenten werden immer im PascalCase benannt, und am besten genau so, wie das File heißt. Also hier schlicht `Button`

2023-08-07 15:57 UTC, Juviro commented on src/Components/Carousel/Carousel.css
> +.react-multi-carousel-track {
**todo:** Leeres ruleset, kann wohl raus

2023-08-07 15:57 UTC, Juviro commented on src/Components/Carousel/Carousel.css
>  #Landing__Products {
**question:** Wird diese id irgendwo verwendet? Ich sehe in der Codebase nichts dazu. Falls ja: Wenn ich global über das Projekt suche, dann muss dort `Landing__Products` an der entsprechenden Stelle auftauchen, damit klar ist, dass dieses ruleset verwendet wird

2023-08-07 15:57 UTC, Juviro commented on src/Components/Navbar/Navbar.jsx
> +    console.log("isDark state:", !isDark);
**todo:** Das console.log kann raus, oder?

2023-08-07 15:57 UTC, Juviro commented on src/Components/Navbar/Navbar.jsx
Ich habe einen commit mit der Funktionalität gemacht. Zwei Sachen fehlten hier:

* Die korrekte id auswählen (du hast als id den string "target-element" verwendet). Damit funktioniert es schon mal, solange wir vorher schon auf der Seite (und nicht auf dem "Contact" Formular waren.
* Falls dies nicht der Fall ist, habe ich in Home.jsx einen Effect hinzugefügt, der beim initialen rendern schaut, ob ein hash gesetzt ist, und falls ja dort hin scrollt

2023-08-07 15:57 UTC, Juviro commented on src/Routes/Contact.css
Ich würde sämtliche Selektoren ändern:

* Keine id's verwenden wenn nicht unbedingt notwendig -> bad practice
* Keine Selektoren auf html Elemente (p, span, etc) -> Sehr fehleranfällig.
* Dinge wie `:first-child` vermeiden wenn nicht notwendig, lieber ein mal mehr eine Klasse setzen -> Fehleranfällig, viel Aufwand bei kleinen Änderungen der html Struktur

2023-08-07 15:57 UTC, Juviro commented on src/Routes/Home.jsx
> +      <Header isDark={isDark} />
**todo:** `Header` braucht diese Prop nicht. `mode--dark` wird bereits auf .app gesetzt und kann deshalb aus der ganzen app selektiert werden. Der Selektor in Header.css muss dann nur von `&.mode--dark {` auf `.mode--dark & {` geändert werden. Dann brauchst du in der Header.jsx nicht noch mal eine Klasse für den Dark mode setzen

2023-08-07 15:57 UTC, Juviro commented on src/main.jsx
> +    // loader: rootLoader,
**question:** Kann das raus oder soll das später wieder einkommentiert werden?

2023-08-09 08:54 UTC, merged